'\" t
.\"     Title: optipng
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 2025-05-20
.\"    Manual: OptiPNG Manual
.\"    Source: optipng 7.9.1
.\"  Language: English
.\"
.TH "OPTIPNG" "1" "2025-05-20" "optipng 7.9.1" "OptiPNG Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
optipng \- optimize Portable Network Graphics (PNG) files
.SH "SYNOPSIS"
.sp
\fBoptipng\fR [<\fIoptions...\fR>] [\-\-] <\fIfiles...\fR>
.SH "DESCRIPTION"
.sp
The OptiPNG program shall attempt to \fIoptimize\fR PNG files, i.e. to reduce their size to a minimum, without losing semantic information. In addition, this program shall perform a suite of auxiliary functions like integrity checks, metadata recovery and pixmap\-to\-PNG conversion.
.sp
The optimization attempts are not guaranteed to succeed. Valid PNG files that cannot be optimized by this program are normally left intact; their size will not grow. The user may request to override this default behavior.
.SH "FILES"
.sp
The input files are raster image files encoded either in PNG format (the native format), or in an external format. The currently supported external formats are GIF, BMP, PNM and TIFF.
.sp
OptiPNG processes each image file given in the command line as follows:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
If the image is in PNG format:
.sp
It attempts to optimize the given file in\-place. If optimization is successful, or if the option
\fB\-force\fR
is enabled, the original file will be replaced by its optimized version. In any case, the original file will be backed up if the option
\fB\-keep\fR
is enabled.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
If the image is in an external format:
.sp
It creates an optimized PNG version of the given file. The output file name will be constructed using the original file name and the
\&.png
extension.
.RE
.sp
Aside from the rules stated above, any existing file is \fInot\fR overwritten, unless the option \fB\-clobber\fR is enabled.
.SH "OPTIONS"
.SS "General options"
.PP
\fB\-?\fR, \fB\-h\fR, \fB\-help\fR
.RS 4
Show a complete summary of options.
.RE
.PP
\fB\-backup\fR, \fB\-keep\fR
.RS 4
Keep a backup of the modified files.
.RE
.PP
\fB\-clobber\fR
.RS 4
Overwrite the existing output and backup files.
.sp
Under this option, if the option
\fB\-backup\fR
is not enabled, the old backups of the overwritten files will be deleted.
.RE
.PP
\fB\-dir\fR \fIdirectory\fR
.RS 4
Write the output files to
\fIdirectory\fR.
.RE
.PP
\fB\-fix\fR
.RS 4
Enable error recovery. This option has no effect on valid input files.
.sp
The program will spend a reasonable amount of effort to recover as much data as possible, without increasing the output file size, but the success cannot be generally guaranteed. The program may even increase the file size, e.g., by reconstructing missing critical data. Under this option, integrity shall take precedence over file size.
.sp
When this option is not used, the invalid input files are left unprocessed.
.RE
.PP
\fB\-force\fR
.RS 4
Enforce writing of a new output file.
.sp
This option overrides the program\(cqs decision not to write such file, e.g. when the PNG input is digitally signed (using dSIG), or when the PNG output becomes larger than the PNG input.
.RE
.PP
\fB\-out\fR \fIfile\fR
.RS 4
Write output file to
\fIfile\fR.
.sp
The command line must contain exactly one input file.
.RE
.PP
\fB\-preserve\fR
.RS 4
Preserve file attributes (time stamps, file access rights, etc.) where applicable.
.RE
.PP
\fB\-quiet\fR, \fB\-silent\fR
.RS 4
Run in quiet mode.
.RE
.PP
\fB\-simulate\fR
.RS 4
Run in simulation mode: perform the trials, but do not create output files.
.RE
.PP
\fB\-v\fR
.RS 4
Enable the options
\fB\-verbose\fR
and
\fB\-version\fR.
.RE
.PP
\fB\-verbose\fR
.RS 4
Run in verbose mode.
.RE
.PP
\fB\-version\fR
.RS 4
Show the copyright, version and build info.
.RE
.PP
\fB\-\-\fR
.RS 4
Stop option switch parsing.
.RE
.SS "PNG encoding and optimization options"
.PP
\fB\-o\fR \fIlevel\fR
.RS 4
Select the optimization level.
.sp
The optimization level 0 enables a set of optimization operations that require minimal effort. There will be no changes to image attributes like bit depth or color type, and no recompression of existing IDAT datastreams.
.sp
The optimization level 1 enables a single IDAT compression trial. The trial chosen is what OptiPNG
\fIthinks\fR
it might be the most effective.
.sp
The optimization levels 2 and higher enable multiple IDAT compression trials; the higher the level, the more trials.
.sp
The behavior and the default value of this option may change across different program versions. Use the option
\fB\-h\fR
to see the details pertaining to your specific version.
.RE
.PP
\fB\-f\fR \fIfilters\fR
.RS 4
Select the PNG delta filters.
.sp
The
\fIfilters\fR
argument is specified as a rangeset (e.g.
\fB\-f0\-5\fR), and the default
\fIfilters\fR
value depends on the optimization level set by the option
\fB\-o\fR.
.sp
The filter values 0, 1, 2, 3 and 4 indicate static filtering, and correspond to the standard PNG filter codes (\fINone\fR,
\fILeft\fR,
\fIUp\fR,
\fIAverage\fR
and
\fIPaeth\fR, respectively). The filter value 5 indicates adaptive filtering, whose effect is defined by the
\fBlibpng\fR(3) library used by OptiPNG.
.RE
.PP
\fB\-full\fR
.RS 4
Produce a full report on IDAT. This option might slow down the trials.
.RE
.PP
\fB\-i\fR \fItype\fR
.RS 4
Select the interlace type (0\-1).
.sp
If the interlace type 0 is selected, the output image shall be non\-interlaced (i.e. progressive\-scanned). If the interlace type 1 is selected, the output image shall be interlaced using the
\fIAdam7\fR
method.
.sp
By default, the output shall have the same interlace type as the input.
.RE
.PP
\fB\-nb\fR
.RS 4
Do not apply bit depth reduction.
.RE
.PP
\fB\-nc\fR
.RS 4
Do not apply color type reduction.
.RE
.PP
\fB\-np\fR
.RS 4
Do not apply palette reduction.
.RE
.PP
\fB\-nx\fR
.RS 4
Do not apply any lossless image reduction: enable the options
\fB\-nb\fR,
\fB\-nc\fR
and
\fB\-np\fR.
.RE
.PP
\fB\-nz\fR
.RS 4
Do not recode IDAT datastreams.
.sp
The IDAT optimization operations that do not require recoding (e.g. IDAT chunk concatenation) are still performed.
.sp
This option has effect on PNG input files only.
.RE
.PP
\fB\-zc\fR \fIlevels\fR
.RS 4
Select the zlib compression levels used in IDAT compression.
.sp
The
\fIlevels\fR
argument is specified as a rangeset (e.g.
\fB\-zc6\-9\fR), and the default
\fIlevels\fR
value depends on the optimization level set by the option
\fB\-o\fR.
.sp
The effect of this option is defined by the
\fBzlib\fR(3) library used by OptiPNG.
.RE
.PP
\fB\-zm\fR \fIlevels\fR
.RS 4
Select the zlib memory levels used in IDAT compression.
.sp
The
\fIlevels\fR
argument is specified as a rangeset (e.g.
\fB\-zm8\-9\fR), and the default
\fIlevels\fR
value depends on the optimization level set by the option
\fB\-o\fR.
.sp
The effect of this option is defined by the
\fBzlib\fR(3) library used by OptiPNG.
.RE
.PP
\fB\-zs\fR \fIstrategies\fR
.RS 4
Select the zlib compression strategies used in IDAT compression.
.sp
The
\fIstrategies\fR
argument is specified as a rangeset (e.g.
\fB\-zs0\-3\fR), and the default
\fIstrategies\fR
value depends on the optimization level set by the option
\fB\-o\fR.
.sp
The effect of this option is defined by the
\fBzlib\fR(3) library used by OptiPNG.
.RE
.PP
\fB\-zw\fR \fIsize\fR
.RS 4
Select the zlib window size (32k,16k,8k,4k,2k,1k,512,256) used in IDAT compression.
.sp
The
\fIsize\fR
argument can be specified either in bytes (e.g. 16384) or kilobytes (e.g. 16k). The default
\fIsize\fR
value is set to the lowest window size that yields an IDAT output as big as if yielded by the value 32768.
.sp
The effect of this option is defined by the
\fBzlib\fR(3) library used by OptiPNG.
.RE
.SS "Editing options"
.PP
\fB\-snip\fR
.RS 4
Cut one image out of multi\-image, animation or video files.
.sp
Depending on the input format, this may be either the first or the most relevant (e.g. the largest) image.
.RE
.PP
\fB\-strip\fR \fIobjects\fR
.RS 4
Strip metadata objects from a PNG file.
.sp
PNG metadata is the information stored in any ancillary chunk except tRNS. (tRNS represents the alpha channel, which, even if ignored in rendering, is still a proper image channel in the RGBA color space.)
.sp
The only option currently supported is
\fB\-strip all\fR.
.RE
.SS "Notes"
.sp
Options may come in any order (except for \fB\-\-\fR), before, after, or alternating with file names. Option names are case\-insensitive and may be abbreviated to their shortest unique prefix.
.sp
Some options may have arguments that follow the option name, separated by whitespace or the equal sign (\fI\fB=\fR\fR). If the option argument is a number or a rangeset, the separator may be omitted. For example:
.sp
.if n \{\
.RS 4
.\}
.nf
optipng \-out newfile.png  <=>  optipng \-out=newfile.png
optipng \-o3  <=>  optipng \-o 3  <=>  optipng \-o=3
optipng \-f0,3\-5  <=>  optipng \-f 0,3\-5  <=>  optipng \-f=0,3\-5
.fi
.if n \{\
.RE
.\}
.sp
Rangeset arguments are cumulative. For example:
.sp
.if n \{\
.RS 4
.\}
.nf
optipng \-f0 \-f3\-5  <=>  optipng \-f0,3\-5
optipng \-zs0 \-zs1 \-zs2,3  <=>  optipng \-zs0\-3
.fi
.if n \{\
.RE
.\}
.SH "EXTENDED DESCRIPTION"
.sp
The PNG optimization algorithm consists of the following steps:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Reduce the bit depth, the color type and the color palette of the image. This step may reduce the size of the uncompressed image, which, indirectly, may reduce the size of the compressed image (i.e. the size of the output PNG file).
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Run a suite of compression methods and strategies and select the compression parameters that yield the smallest output file.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Store all IDAT contents into a single chunk, eliminating the overhead incurred by repeated IDAT headers and CRCs.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
Set the zlib window size inside IDAT to a minimum that does not affect the compression ratio, reducing the memory requirements of PNG decoders.
.RE
.sp
Not all of the above steps need to be executed. The behavior depends on the actual input files and user options.
.sp
Step 1 may be customized via the no\-reduce options \fB\-nb\fR, \fB\-nc\fR, \fB\-np\fR and \fB\-nx\fR. Step 2 may be customized via the \fB\-o\fR option, and may be fine\-tuned via the options \fB\-zc\fR, \fB\-zm\fR, \fB\-zs\fR and \fB\-zw\fR. Step 3 is always executed. Step 4 is executed only if a new IDAT is being created, and may be fine\-tuned via the option \fB\-zw\fR.
.sp
Extremely exhaustive searches are not generally expected to yield significant improvements in compression ratio, and are recommended to advanced users only.
.SH "EXAMPLES"
.sp
.if n \{\
.RS 4
.\}
.nf
optipng file.png      # default speed
optipng \-o5 file.png  # slow
optipng \-o7 file.png  # very slow
.fi
.if n \{\
.RE
.\}
.SH "BUGS"
.sp
Lossless image reductions are not completely implemented. (This does \fInot\fR affect the integrity of the output files.) Here are the missing pieces:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
The color palette reductions are implemented only partially.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
The bit depth reductions below 8, for grayscale images, are not implemented yet.
.RE
.sp
Encoding of images whose total IDAT size exceeds 2GB is not currently supported.
.sp
TIFF support is limited to uncompressed, PNG\-compatible (grayscale, RGB and RGBA) images.
.sp
Metadata is not imported from the external image formats.
.sp
There is no support for pipes, streams, extended file attributes or access control lists.
.SH "SEE ALSO"
.sp
\fBpng\fR(5), \fBlibpng\fR(3), \fBzlib\fR(3), \fBpngcrush\fR(1), \fBpngrewrite\fR(1).
.SH "STANDARDS"
.sp
The files produced by OptiPNG are compliant with the most recent PNG standard ("PNG Second Edition"), as well as the most recent PNG draft standard ("PNG Third Edition").
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIPortable Network Graphics (PNG) Specification, Second Edition\fR.
.br
W3C Recommendation 10 November 2003; ISO/IEC IS 15948:2003 (E).
.br
https://www.w3.org/TR/2003/REC\-PNG\-20031110/
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIPortable Network Graphics (PNG) Specification, Third Edition\fR.
.br
W3C Proposed Recommendation 15 May 2025.
.br
https://www.w3.org/TR/2025/PR\-png\-3\-20250515/
.RE
.SH "AUTHORS"
.sp
OptiPNG is written and maintained by Cosmin Truta.
.sp
This manual page was originally written by Nelson A. de Oliveira for the Debian Project. It was later updated by Cosmin Truta, and is now part of the OptiPNG distribution.
