name: CI

on:
  push:
  pull_request:

env:
  FORCE_COLOR: 2

jobs:
  ci:
    runs-on: windows-latest
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Build
        run: CALL "build.bat"
        shell: cmd

      - name: Prepare files
        run: |
          mkdir dist
          cp -r doc/ src/optipng/optipng.exe LICENSE.txt README.txt dist/
        shell: bash

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: "optipng"
          path: dist/
          if-no-files-found: error
