name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2

jobs:
  ci:
    runs-on: windows-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Build
        run: CALL "build.bat"
        shell: cmd

      - name: Prepare files
        run: |
          mkdir dist
          cp -r doc/ src/optipng/optipng.exe LICENSE.txt README.txt dist/
        shell: bash

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: "optipng"
          path: dist/
          if-no-files-found: error
